language: python
python:
  - "2.7"
before_install:
  - wget http://de.archive.ubuntu.com/ubuntu/pool/main/s/snappy/libsnappy1_1.0.5-2_amd64.deb
  - wget http://de.archive.ubuntu.com/ubuntu/pool/main/s/snappy/libsnappy-dev_1.0.5-2_amd64.deb
  - wget http://de.archive.ubuntu.com/ubuntu/pool/main/l/leveldb/libleveldb1_1.9.0-1_amd64.deb
  - wget http://de.archive.ubuntu.com/ubuntu/pool/main/l/leveldb/libleveldb-dev_1.9.0-1_amd64.deb
  - sudo dpkg -i libsnappy1_1.0.5-2_amd64.deb
  - sudo dpkg -i libsnappy-dev_1.0.5-2_amd64.deb
  - sudo dpkg -i libleveldb1_1.9.0-1_amd64.deb
  - sudo dpkg -i libleveldb-dev_1.9.0-1_amd64.deb
install:
  - pip install -r requirements.txt
script:
  - python test.py
