language: python
python:
  - "2.7"
env:
  - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$TRAVIS_BUILD_DIR/leveldb-1.15.0
before_install:
  - wget -O leveldb.tgz https://leveldb.googlecode.com/files/leveldb-1.15.0.tar.gz
  - tar -xf leveldb.tgz
  - cd leveldb-1.15.0
  - make
  - pip install -r requirements.txt
script: test.py
